[package]
name = "geometry"
version = "0.1.0"
authors = ["Alex Peyrard <alex.peyrard@smart-side.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
